# Generated by Django 4.1 on 2022-08-20 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman', models.CharField(default=False, max_length=100, verbose_name='Продавец')),
                ('provider', models.CharField(default=False, max_length=100, verbose_name='Поставщик')),
                ('user_type', models.CharField(max_length=100, verbose_name='ИП или Юр.лицо')),
                ('inn', models.CharField(max_length=15, verbose_name='ИИН')),
                ('city', models.CharField(max_length=50, verbose_name='Ваш город')),
                ('the_outside', models.CharField(max_length=100, verbose_name='Улица')),
                ('home_residential', models.CharField(max_length=100, verbose_name='Дом/стр.')),
                ('office', models.CharField(max_length=100, verbose_name='Офис')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('fax_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
