# Generated by Django 4.1 on 2022-08-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
