# Generated by Django 4.1 on 2022-08-20 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0004_alter_register_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Регистрация', 'verbose_name_plural': 'Регистрации'},
        ),
        migrations.AddField(
            model_name='register',
            name='car_service',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Автосервис'),
        ),
        migrations.AddField(
            model_name='register',
            name='federal_store_chain',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Федеральная сеть магазина'),
        ),
        migrations.AddField(
            model_name='register',
            name='online_store',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Интернет-магазин'),
        ),
        migrations.AddField(
            model_name='register',
            name='other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Прочее'),
        ),
        migrations.AddField(
            model_name='register',
            name='regional_chain_store',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Региональная сеть магазина'),
        ),
        migrations.AddField(
            model_name='register',
            name='score',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='register',
            name='site',
            field=models.CharField(default=1, max_length=100, verbose_name='Сайт Вашей компании'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
