# Generated by Django 4.1 on 2022-08-20 20:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0005_alter_register_options_register_car_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=100, verbose_name='ИП или Юр.лицо')),
                ('inn', models.CharField(max_length=15, verbose_name='ИИН')),
                ('city', models.CharField(max_length=50, verbose_name='Ваш город')),
                ('the_outside', models.CharField(max_length=100, verbose_name='Улица')),
                ('home_residential', models.CharField(max_length=100, verbose_name='Дом/стр.')),
                ('office', models.CharField(max_length=100, verbose_name='Офис')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефона необходимо вводить в формате: «+999999999». Допускается до 15 цифр.', regex='^\\+?1?\\d{9,15}$')])),
                ('score', models.BooleanField(blank=True, default=False, null=True, verbose_name='Магазин')),
                ('regional_chain_store', models.BooleanField(blank=True, default=False, null=True, verbose_name='Региональная сеть магазина')),
                ('federal_store_chain', models.BooleanField(blank=True, default=False, null=True, verbose_name='Федеральная сеть магазина')),
                ('online_store', models.BooleanField(blank=True, default=False, null=True, verbose_name='Интернет-магазин')),
                ('car_service', models.BooleanField(blank=True, default=False, null=True, verbose_name='Автосервис')),
                ('other', models.CharField(blank=True, max_length=200, null=True, verbose_name='Прочее')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='RegisterProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=100, verbose_name='ИП или Юр.лицо')),
                ('inn', models.CharField(max_length=15, verbose_name='ИИН')),
                ('city', models.CharField(max_length=50, verbose_name='Ваш город')),
                ('the_outside', models.CharField(max_length=100, verbose_name='Улица')),
                ('home_residential', models.CharField(max_length=100, verbose_name='Дом/стр.')),
                ('office', models.CharField(max_length=100, verbose_name='Офис')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефона необходимо вводить в формате: «+999999999». Допускается до 15 цифр.', regex='^\\+?1?\\d{9,15}$')])),
                ('score', models.BooleanField(blank=True, default=False, null=True, verbose_name='Магазин')),
                ('regional_chain_store', models.BooleanField(blank=True, default=False, null=True, verbose_name='Региональная сеть магазина')),
                ('federal_store_chain', models.BooleanField(blank=True, default=False, null=True, verbose_name='Федеральная сеть магазина')),
                ('online_store', models.BooleanField(blank=True, default=False, null=True, verbose_name='Интернет-магазин')),
                ('car_service', models.BooleanField(blank=True, default=False, null=True, verbose_name='Автосервис')),
                ('other', models.CharField(blank=True, max_length=200, null=True, verbose_name='Прочее')),
                ('site', models.CharField(max_length=100, verbose_name='Сайт Вашей компании')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
