# Generated by Django 4.1 on 2022-08-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_registerbuyer_registerprovider_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerbuyer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registerprovider',
            name='user',
        ),
        migrations.AddField(
            model_name='registerbuyer',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Эл.почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerprovider',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Эл.почта'),
            preserve_default=False,
        ),
    ]
