# Generated by Django 4.1 on 2022-08-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_registerbuyer_phone_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerbuyer',
            name='phone_code',
            field=models.CharField(choices=[('Кыргызстан', '+996'), ('Казахстан', '+7'), ('Армения', '+374'), ('Узбекистан', '+998'), ('Украина', '+380'), ('Польша', '+48'), ('Китай', '+86'), ('Германия', '+49'), ('Соединенные Штаты Америки', '+1'), ('Великобритания', '+44')], default=('Росиия', '+7'), max_length=100, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='registerprovider',
            name='phone_code',
            field=models.CharField(choices=[('Кыргызстан', '+996'), ('Казахстан', '+7'), ('Армения', '+374'), ('Узбекистан', '+998'), ('Украина', '+380'), ('Польша', '+48'), ('Китай', '+86'), ('Германия', '+49'), ('Соединенные Штаты Америки', '+1'), ('Великобритания', '+44')], default=('Росиия', '+7'), max_length=100, verbose_name='Код'),
        ),
    ]
