# Generated by Django 4.1 on 2022-08-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_alter_registerbuyer_phone_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerbuyer',
            name='car_service',
            field=models.BooleanField(blank=True, null=True, verbose_name='Автосервис'),
        ),
        migrations.AlterField(
            model_name='registerprovider',
            name='car_service',
            field=models.BooleanField(blank=True, null=True, verbose_name='Автосервис'),
        ),
    ]
