# Generated by Django 4.1 on 2022-08-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_registerbuyer_boo_registerprovider_boo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerbuyer',
            name='boo',
        ),
        migrations.RemoveField(
            model_name='registerprovider',
            name='boo',
        ),
        migrations.AlterField(
            model_name='registerbuyer',
            name='car_service',
            field=models.BooleanField(blank=True, default='', null=True, verbose_name='Автосервис'),
        ),
        migrations.AlterField(
            model_name='registerbuyer',
            name='federal_store_chain',
            field=models.BooleanField(blank=True, default='', null=True, verbose_name='Федеральная сеть магазина'),
        ),
        migrations.AlterField(
            model_name='registerbuyer',
            name='online_store',
            field=models.BooleanField(blank=True, default='', null=True, verbose_name='Интернет-магазин'),
        ),
        migrations.AlterField(
            model_name='registerbuyer',
            name='regional_chain_store',
            field=models.BooleanField(blank=True, default='', null=True, verbose_name='Региональная сеть магазина'),
        ),
        migrations.AlterField(
            model_name='registerbuyer',
            name='score',
            field=models.BooleanField(blank=True, default='', null=True, verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='registerprovider',
            name='car_service',
            field=models.BooleanField(blank=True, default='', null=True, verbose_name='Автосервис'),
        ),
        migrations.AlterField(
            model_name='registerprovider',
            name='federal_store_chain',
            field=models.BooleanField(blank=True, default='', null=True, verbose_name='Федеральная сеть магазина'),
        ),
        migrations.AlterField(
            model_name='registerprovider',
            name='online_store',
            field=models.BooleanField(blank=True, default='', null=True, verbose_name='Интернет-магазин'),
        ),
        migrations.AlterField(
            model_name='registerprovider',
            name='regional_chain_store',
            field=models.BooleanField(blank=True, default='', null=True, verbose_name='Региональная сеть магазина'),
        ),
        migrations.AlterField(
            model_name='registerprovider',
            name='score',
            field=models.BooleanField(blank=True, default='', null=True, verbose_name='Магазин'),
        ),
    ]
