# Generated by Django 4.1 on 2022-08-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_registerbuyer_boo_registerprovider_boo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerbuyer',
            name='car_service',
            field=models.BooleanField(default=False, verbose_name='Автосервис'),
        ),
        migrations.AlterField(
            model_name='registerbuyer',
            name='score',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='registerprovider',
            name='car_service',
            field=models.BooleanField(default=False, verbose_name='Автосервис'),
        ),
        migrations.AlterField(
            model_name='registerprovider',
            name='score',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Магазин'),
        ),
    ]
