# Generated by Django 4.1 on 2022-08-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_alter_registerbuyer_car_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerbuyer',
            name='phone_number',
            field=models.IntegerField(blank=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='registerprovider',
            name='phone_number',
            field=models.IntegerField(blank=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='registerprovider',
            name='site',
            field=models.URLField(max_length=100, verbose_name='Сайт Вашей компании'),
        ),
    ]
