# Generated by Django 4.1 on 2022-08-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0019_alter_registerbuyer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerprovider',
            name='site',
            field=models.URLField(blank=True, max_length=100, verbose_name='Сайт Вашей компании'),
        ),
    ]
